import time
import subprocess
subprocess.run(["sudo", "apt", "update"])
subprocess.run(["sudo", "apt", "install", "wordlists"])
subprocess.run(["git", "clone", "https://github.com/kennyn510/wpa2-wordlists.git", "&&", "cd", "wpa2-wordlists/Wordlists/Rockyou", "&&", "gunzip", "*.gz", "&&", "cat", "*.txt>>full.txt"])
subprocess.run(["sudo", "apt", "install", "aircrack-ng"])
subprocess.run(["sudo", "apt", "install", "wifipumpkin3"])
subprocess.run(["sudo", "apt", "install", "whatweb"])
subprocess.run(["sudo", "apt", "install", "pwned"])
subprocess.run(["sudo", "apt", "install", "sshuttle"])
subprocess.run(["sudo", "apt", "install", "dnsrecon"])
subprocess.run(["sudo", "apt", "install", "dnsenum"])
subprocess.run(["sudo", "apt", "install", "theHarvester"])
subprocess.run(["sudo", "apt", "install", "wapiti"])
subprocess.run(["sudo", "apt", "install", "commix"])
subprocess.run(["sudo", "apt", "install", "sqlmap"])
subprocess.run(["sudo", "apt", "install", "holehe"])
subprocess.run(["sudo", "apt", "install", "socialscan"])
subprocess.run(["sudo", "apt", "install", "mailsniper"])
subprocess.run(["sudo", "apt", "install", "sherlock"])
subprocess.run(["sudo", "apt", "install", "userrecon"])
subprocess.run(["sudo", "apt", "install", "whatsmyname"])
print("system updated & up to 17 packages installed...")
print("happy hacking ;)")
time.sleep(3)
subprocess.run(["clear"])
subprocess.run(["sudo", "python3", "redridinghood.py"])
